### ISSUE TITLE
Afternoon exercise

### ISSUE THREAD

**Issue by datapolitan** [datapolitan/DOT_GIS#18]
Bike accidents on bike lanes vs not

**Comment by eapappas** [comment]
content done, screen shots tomorrow
@datapolitan what should the buffer be?  you had said 15 feet but that seems like a large buffer, no?

**Comment by datapolitan** [comment]
That works well for the bike injuries exercise. I actually let them pick what they think is reasonable to buffer when I do it in class but have 15 in the slides

**Comment by eapappas** [comment]
@datapolitan, I can't work out how to make this exercise work well with clipping.  It seems it's an intersection  followed by a diff, or a spatial join.  Am I being remedial?  Please advise.
