### ISSUE TITLE
nycd_16a into 2263

### ISSUE THREAD

**Issue by datapolitan** [datapolitan/DOT_GIS#49]

**Comment by eapappas** [comment]
@datapolitan - I thought this was to be the 311 complaints?  All of the files in the nycd_16a folder are .CSVs.

Further to the 311 complaints - the CRS in dot-311-20160201-20160207 is defined as 4326.  Was that the point here?  To change that one to 2263 too?   (I had thought for both of these issues, it was to get rid of the user-defined nonsense.)  Please advise and I can do it quickly.

**Comment by datapolitan** [comment]
@eapappas I don't know where you're seeing the CSVs. They are all there and the file loads as intended. Thanks for taking care of this. The 311 should stay in 4326. No worries there.
