### ISSUE TITLE
Add different example of choropleths / counting points in polygons

### ISSUE THREAD

**Issue by ebrelsford** [datapolitan/DOT_GIS#67]
[eg](http://2.bp.blogspot.com/-C1Sc-8q_yWw/T_RV9Pe-m1I/AAAAAAAABPY/KA2E-vu8OO4/s1600/twitterbeerchurchfixed.jpg)

**Comment by datapolitan** [comment]
@ebrelsford Did you mean to assign this to Data Vis or the Intro class?

**Comment by ebrelsford** [comment]
@datapolitan good catch, definitely Intro!

**Comment by datapolitan** [comment]
@ebrelsford Are you going to be able to get this done soon? (I'd like to finalize the book soon)

**Comment by ebrelsford** [comment]
@richarddunks yes, working on it now.
