### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ebrelsford** [datapolitan/DOT_GIS#79]
Review of basic concepts:
- [ ] What is geographic data 
- [ ] What is GIS

**Comment by datapolitan** [comment]
@ebrelsford should we cover thematic/reference, esp choropleths? We could do this after they create one as a reminder of what it's called and show another example.

**Comment by ebrelsford** [comment]
@datapolitan: wouldn't hurt, I'll work that in.

**Comment by datapolitan** [comment]
@ebrelsford Looks good. I think this is pretty much closed.  What do you think?

**Comment by ebrelsford** [comment]
@datapolitan works for me!
