### ISSUE TITLE
Practical Excercise 1

### ISSUE THREAD

**Issue by ebrelsford** [datapolitan/DOT_GIS#80]
- [ ] Open a basemap in QGIS
- [ ] Import a shapefile in QGIS
- [ ] Import CSV data to QGIS
- [ ] Review projections
- [ ] Basic styling in QGIS

**Comment by datapolitan** [comment]
@ebrelsford How much more do we want to add to this than what's already in the intro course?

**Comment by ebrelsford** [comment]
Pretty much should just do what's in the intro course, I'll push a stab at that.

**Comment by datapolitan** [comment]
We should add in the basemap steps. They should already have QMS installed, but walk them through. The shapefile should probably be the boros shapefile and the CSV can be the 311 complaints. That way they hit all the elements.

**Comment by datapolitan** [comment]
@ebrelsford Look over this and tell me what you think. I reworked the Your Turn into a follow along exercise to get them acquainted with the basic loading of features. Then gave them the a release to play and style as they wanted. Let me know what you think and if you're good with it, go ahead and close this out.

**Comment by ebrelsford** [comment]
Looks good to me, @datapolitan
