### ISSUE TITLE
Intro to spatial databases

### ISSUE THREAD

**Issue by ebrelsford** [datapolitan/DOT_GIS#81]
- [ ] When have you used a spatial database?
- [ ] What is a spatial database? (like a shared file server)
- [ ] A quick and simple introduction to the relational model
- [ ] Sharing data with datbases
- [ ] Introduction to schemas (as relate to datatypes in SHP)
- [ ] Performance benefits of databases

**Comment by ebrelsford** [comment]
@datapolitan I fleshed this out a bit, could definitely use some screenshots for connecting to a database from QGIS

**Comment by datapolitan** [comment]
Already done. By the way, the credentials are in the slides for connecting

**Comment by datapolitan** [comment]
@ebrelsford This looks good. Thanks for the extra content.
