### ISSUE TITLE
Introduction to SQL

### ISSUE THREAD

**Issue by ebrelsford** [datapolitan/DOT_GIS#84]
- [x] A basic introduction to SQL
- [x] Select query for features in single table
- [ ] Introduction to PostGIS and spatial SQL
- [ ] Introduction to PostGIS functions

**Comment by datapolitan** [comment]
@ebrelsford It looks like the SQL queries in this section don't match the new schema (uses `training` schema rather than public). It would also be great if these more closely mirrored what we did in PE3 (the bicycle injuries exercise) and include normalizing data for the choropleth.

**Comment by ebrelsford** [comment]
Fixed the schema.
