### ISSUE TITLE
Wrap-up

### ISSUE THREAD

**Issue by ebrelsford** [datapolitan/DOT_GIS#87]
- [x] Discussion of data formats
- [x] Introduce PostGIS documentation and other resources
- [x] Quick demonstration of model builder in QGIS
- [x] Discuss geocoding of addresses in QGIS

**Comment by datapolitan** [comment]
@ebrelsford Realistically, how much can we cover in the class given the time we have left?

**Comment by ebrelsford** [comment]
@datapolitan I think we have another 30 minutes or so we could use. It depends on how long we give them to make maps on their own. Maybe we pick one (model builder or geocoder) to add?

**Comment by datapolitan** [comment]
@ebrelsford How about we demo the geocoder and give them a resource for model builder?

**Comment by ebrelsford** [comment]
Works for me @richarddunks do you have a file you like to use for geocoding? If not I can find one. Just pushed some slides.

I will have to look a bit more for a modeler resource, many use rasters or extra complicated expressions and don't feel appropriate.

**Comment by datapolitan** [comment]
@ebrelsford Awesome. I have the [Lincoln Center BID data](https://github.com/datapolitan/DOT_GIS/blob/gh-pages/20160413_Introduction_to_GIS_Fundamentals/data/Lincoln_Square_BID_Business_List.csv) that I threw into the first Intro class but didn't use. It doesn't need to be complicated. In fact it's best if it isn't.

**Comment by datapolitan** [comment]
And if modeling is too much, we can just tell them what it is and let them go forth and find their own resources. I'm also happy with dropping it.

**Comment by ebrelsford** [comment]
Cool, I added a link to the BID data. Seems fine if we don't get to it or the model builder since they're bonuses. If we feel like there's a lot of time left I can improvise a model builder session, too.

**Comment by datapolitan** [comment]
@ebrelsford That sounds like a good plan. Still to do:
- [x] Data formats
- [x] When might see it 
- [x] PostGIS docs
